export const fetchCache = "force-no-store";
export const revalidate = 0;
export const maxDuration = 300;

import ComponentCard from "@/components/component-card";
import { Container } from "@/components/container";
import { PageTitle } from "@/components/page-title";

import { getAllVuePublicChats } from "../actions";

export const metadata = {
  title: `Public Vue components - Tailwind AI`,
  description:
    "Last Tailwind Vue components generated with AI by our users with Vue and Tailwind CSS",
};

export default async function VueComponents() {
  const chats = await getAllVuePublicChats();
  return (
    <Container className="pr-2 sm:pr-11">
      <PageTitle
        title="Vue Components"
        subtitle="Last Vue components generated by our users"
      />
      <div className="grid grid-cols-1 gap-x-4 gap-y-10 pb-20 lg:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">
        {chats?.map((chat) => <ComponentCard key={chat.chat_id} chat={chat} />)}
      </div>
    </Container>
  );
}
