import { AppFooter } from "@/components/app-footer";
import { Container } from "@/components/container";
import { PageTitle } from "@/components/page-title";

export const metadata = {
  title: "Terms of Service - CodeRocket",
  description:
    "Terms of Service for CodeRocket AI-powered component generation platform.",
};

export default function TermsPage() {
  return (
    <Container className="w-full">
      <PageTitle
        title="Terms of Service"
        subtitle="Last updated: December 2024"
      />

      <div className="prose prose-gray dark:prose-invert max-w-none">
        <div className="space-y-8">
          <section>
            <h2 className="mb-4 text-2xl font-semibold">
              1. Acceptance of Terms
            </h2>
            <p>
              By accessing and using CodeRocket (&quot;the Service&quot;), you
              accept and agree to be bound by the terms and provision of this
              agreement. If you do not agree to abide by the above, please do
              not use this service.
            </p>
          </section>

          <section>
            <h2 className="mb-4 text-2xl font-semibold">
              2. Description of Service
            </h2>
            <p>
              CodeRocket is an AI-powered platform that generates UI components
              based on user prompts. Users can create and modify components for
              their own projects.
            </p>
          </section>

          <section>
            <h2 className="mb-4 text-2xl font-semibold">3. User Accounts</h2>
            <div className="space-y-3">
              <p>
                <strong>3.1 Registration:</strong> You must provide accurate and
                complete information when creating an account.
              </p>
              <p>
                <strong>3.2 Account Security:</strong> You are responsible for
                maintaining the confidentiality of your account credentials.
              </p>
              <p>
                <strong>3.3 Account Usage:</strong> You are responsible for all
                activities that occur under your account.
              </p>
            </div>
          </section>

          <section>
            <h2 className="mb-4 text-2xl font-semibold">4. Acceptable Use</h2>
            <p>You agree not to use the Service to:</p>
            <ul className="list-disc space-y-2 pl-6">
              <li>
                Generate content that is illegal, harmful, or violates
                intellectual property rights
              </li>
              <li>Attempt to reverse engineer or compromise our AI models</li>
              <li>
                Upload malicious code or engage in any form of cyber attack
              </li>
              <li>Spam, harass, or abuse other users</li>
              <li>Violate any applicable laws or regulations</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-4 text-2xl font-semibold">
              5. Content and Intellectual Property
            </h2>
            <div className="space-y-3">
              <p>
                <strong>5.1 User-Generated Content:</strong> You retain
                ownership of the content you create using our Service, but you
                grant us a license to use, store, and display it as necessary to
                provide the Service.
              </p>
              <p>
                <strong>5.2 AI-Generated Components:</strong> Components
                generated by our AI are provided under a permissive license for
                your use, but you are responsible for ensuring compliance with
                any third-party intellectual property rights.
              </p>
              <p>
                <strong>5.3 Platform Content:</strong> Our platform, including
                the AI models, interface, and underlying technology, remains our
                intellectual property.
              </p>
            </div>
          </section>

          <section>
            <h2 className="mb-4 text-2xl font-semibold">6. Payment Terms</h2>
            <div className="space-y-3">
              <p>
                <strong>6.1 Subscription Fees:</strong> Subscription fees are
                billed in advance on a monthly or annual basis, as selected by
                you. Fees are charged automatically at the beginning of each
                billing cycle.
              </p>
              <p>
                <strong>6.2 Refunds:</strong> Subscription fees are
                non-refundable except as required by law or at our sole
                discretion. If you cancel your subscription, you will continue
                to have access to the Service until the end of your current
                billing period.
              </p>
              <p>
                <strong>6.3 Price Changes:</strong> We reserve the right to
                modify our pricing at any time. We will provide at least 30
                days&apos; notice of any price changes. Continued use of the
                Service after the price change constitutes acceptance of the new
                pricing.
              </p>
              <p>
                <strong>6.4 Taxes:</strong> You are responsible for any
                applicable taxes, duties, or fees imposed by your jurisdiction
                on your purchases or earnings.
              </p>
            </div>
          </section>

          <section>
            <h2 className="mb-4 text-2xl font-semibold">
              7. Service Availability
            </h2>
            <div className="space-y-3">
              <p>
                <strong>7.1 Availability:</strong> We strive to maintain the
                Service available 24/7, but we do not guarantee uninterrupted
                access. The Service may be unavailable due to maintenance,
                updates, or unforeseen circumstances.
              </p>
              <p>
                <strong>7.2 Modifications:</strong> We reserve the right to
                modify, suspend, or discontinue any part of the Service at any
                time, with or without notice.
              </p>
            </div>
          </section>

          <section>
            <h2 className="mb-4 text-2xl font-semibold">8. Privacy</h2>
            <p>
              Your privacy is important to us. Please review our Privacy Policy,
              which also governs your use of the Service, to understand our
              practices.
            </p>
          </section>

          <section>
            <h2 className="mb-4 text-2xl font-semibold">9. Disclaimers</h2>
            <div className="space-y-3">
              <p>
                <strong>9.1 Service Availability:</strong> We do not guarantee
                that the Service will be available at all times or free from
                interruptions.
              </p>
              <p>
                <strong>9.2 AI Accuracy:</strong> While we strive for accuracy,
                AI-generated content may contain errors or may not meet your
                specific requirements.
              </p>
              <p>
                <strong>9.3 Third-Party Content:</strong> We are not responsible
                for the accuracy or legality of user-generated content.
              </p>
            </div>
          </section>

          <section>
            <h2 className="mb-4 text-2xl font-semibold">
              10. Limitation of Liability
            </h2>
            <p>
              To the maximum extent permitted by law, CodeRocket shall not be
              liable for any indirect, incidental, special, consequential, or
              punitive damages, or any loss of profits or revenues, whether
              incurred directly or indirectly.
            </p>
          </section>

          <section>
            <h2 className="mb-4 text-2xl font-semibold">11. Termination</h2>
            <div className="space-y-3">
              <p>
                <strong>11.1 Termination by You:</strong> You may terminate your
                account at any time by contacting us.
              </p>
              <p>
                <strong>11.2 Termination by Us:</strong> We may terminate or
                suspend your account for violations of these terms or for any
                other reason at our discretion.
              </p>
              <p>
                <strong>11.3 Effect of Termination:</strong> Upon termination,
                you will lose access to the Service, but your purchased
                components will remain available for download for 30 days.
              </p>
            </div>
          </section>

          <section>
            <h2 className="mb-4 text-2xl font-semibold">
              12. Changes to Terms
            </h2>
            <p>
              We reserve the right to modify these terms at any time. We will
              notify users of significant changes via email or through the
              Service. Continued use of the Service after changes constitutes
              acceptance of the new terms.
            </p>
          </section>

          <section>
            <h2 className="mb-4 text-2xl font-semibold">13. Governing Law</h2>
            <p>
              These Terms of Service shall be governed by and construed in
              accordance with the laws of the jurisdiction in which CodeRocket
              operates, without regard to its conflict of law provisions. Any
              disputes arising from these terms shall be subject to the
              exclusive jurisdiction of the competent courts in that
              jurisdiction.
            </p>
          </section>

          <section>
            <h2 className="mb-4 text-2xl font-semibold">
              14. Contact Information
            </h2>
            <p>
              If you have any questions about these Terms of Service, please
              contact us at:
            </p>
            <div className="rounded-lg bg-gray-50 p-4 dark:bg-gray-800">
              <p>
                <strong>Email:</strong> alexandrelecorre.pro@gmail.com
              </p>
              <p>
                <strong>Website:</strong> https://www.coderocket.app
              </p>
            </div>
          </section>
        </div>
      </div>
      <AppFooter />
    </Container>
  );
}
