import Image from "next/image";
import Link from "next/link";

import type { Chat } from "@/app/(default)/chats/types";
import { getRelativeDate } from "@/utils/date";
import { capitalizeFirstLetter } from "@/utils/helpers";

import { HoverCard, HoverCardTrigger, HoverCardContent } from "./ui/hover-card";

export default function ChatCard({ chat }: { chat: Chat }) {
  return (
    <HoverCard key={chat.chat_id}>
      <HoverCardTrigger asChild>
        <div className="relative aspect-video w-full">
          {chat.last_assistant_message?.screenshot && (
            <Image
              src={chat.last_assistant_message.screenshot}
              fill
              className="w-full rounded-md border object-cover shadow-md"
              alt=""
            />
          )}
          <Link
            href={`/chats/${chat.chat_id}`}
            className="group absolute inset-0 z-10 flex cursor-pointer select-none items-end justify-end rounded-md bg-background/25 transition-all duration-300 hover:bg-transparent"
          >
            <h2 className="m-2 text-xs font-semibold text-foreground group-hover:hidden">
              {capitalizeFirstLetter(chat.first_user_message.content, 50)}
            </h2>
          </Link>
        </div>
      </HoverCardTrigger>
      <HoverCardContent className="w-80">
        <p className="mb-1">{chat.first_user_message.content}</p>
        {chat.created_at && (
          <p className="text-sm font-medium text-muted-foreground">
            {getRelativeDate(chat.created_at)}
          </p>
        )}
        {chat.user_full_name && (
          <p className="text-sm font-medium text-muted-foreground">
            generated by {chat.user_full_name}
          </p>
        )}
      </HoverCardContent>
    </HoverCard>
  );
}
