export function partialIframeBuilder(
  files: {
    name: string | null;
    content: string;
  }[],
) {
  if (!files) {
    return [];
  }
  return files;
}

export const iframeBuilder = (
  files: {
    name: string | null;
    content: string;
  }[],
  id: string,
) => {
  return `<!--
*********************************************************************
* Generated by TailwindAI.dev *
* Component Link *
https://tailwindai.dev/components/${id}
*********************************************************************
-->
  ${partialIframeBuilder(files)}
  `;
};
