export function partialIframeBuilder(
  files: {
    name: string | null;
    content: string;
  }[],
  theme: string,
) {
  if (!files) {
    return "";
  }

  const completion = files.map((file) => file.content).join("");
  return `<html data-theme="${theme}">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/daisyui@4.12.22/dist/full.min.css" rel="stylesheet" type="text/css" />
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  ${completion}
</html>`;
}

export const iframeBuilder = (
  files: {
    name: string | null;
    content: string;
  }[],
  id: string,
  theme: string,
) => {
  return `<!--
*********************************************************************
* Generated by TailwindAI.dev *
* Component Link *
https://tailwindai.dev/components/${id}
*********************************************************************
-->
  ${partialIframeBuilder(files, theme)}
  `;
};
