export function partialIframeBuilder(completion: string, theme: string) {
  if (!completion) {
    return "";
  }

  return `<html data-theme="${theme}">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/daisyui@4.12.19/dist/full.min.css" rel="stylesheet" type="text/css" />
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.1/css/all.min.css" integrity="sha512-5Hs3dF2AEPkpNAR7UiOHba+lRSJNeM2ECkwxUIxC1Q/FLycGTbNapWXB4tP889k5T5Ju8fs4b1P5z/iB4nMfSQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.7/dist/chart.umd.min.js"></script>
  </head>
  ${completion}
</html>`;
}

export const iframeBuilder = (
  completion: string,
  id: string,
  theme: string,
) => {
  return `<!--
*********************************************************************
* Generated by TailwindAI.dev *
* Component Link *
https://tailwindai.dev/components/${id}
*********************************************************************
-->
  ${partialIframeBuilder(completion, theme)}
  `;
};
