import ComponentCard from "@/components/component-card";
import { Container } from "@/components/container";
import { PageTitle } from "@/components/page-title";

import { getAllPublicChats } from "./actions";

export const metadata = {
  title: `Public components - Tailwind AI`,
  description: "Last Tailwind components generated with AI by our users",
};

export default async function Featured() {
  const chats = await getAllPublicChats();
  console.log("chats", chats);
  return (
    <Container>
      <PageTitle
        title="Browse Components"
        subtitle="Last components generated by our users"
      />
      <div className="grid grid-cols-1 gap-3 pb-20 md:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4">
        {chats?.map((chat) => <ComponentCard key={chat.chat_id} chat={chat} />)}
      </div>
    </Container>
  );
}
