import { Container } from "@/components/container";
import { PageTitle } from "@/components/page-title";

import { getAllPublicChats, getAllPopularPublicChats } from "./actions";
import ComponentsInfiniteScroll from "./components-infinite-scroll";

export const metadata = {
  title: "Public components - Tailwind AI",
  description:
    "Last Tailwind components generated with AI by our users with React and HTML",
};

export default async function Components() {
  const initialChats = await getAllPublicChats();
  const initialPopularChats = await getAllPopularPublicChats();

  return (
    <Container className="pr-2 sm:pr-11">
      <PageTitle
        title="Public Components"
        subtitle="Last components generated by our users"
      />
      <ComponentsInfiniteScroll
        initialChats={initialChats}
        initialPopularChats={initialPopularChats}
      />
    </Container>
  );
}
